#!/bin/bash

# Run a configuration n times with 600 iterations 

# Cyan and no color
COLOR='\033[0;36m'
NC='\033[0m'

CONFIGURATION_FILE="$PWD/$2"
BUILD_FILE="$PWD/builds/build-$1/sensor-positioning.dll"
SIMULATION="$BUILD_FILE:SensorPositioning.StaticSpSimulation"

echo -e "${COLOR}Build${NC}: $SIMULATION"
echo -e "${COLOR}Configuration${NC}: $CONFIGURATION_FILE"
echo -e "${COLOR}Iterations${NC}:" $3
echo -e "${COLOR}Runs${NC}:" 600
echo -e "${COLOR}Output directory:${NC}:" $4

# simulation, iterations, runs, config_file, result_dir_name
charlie --run $SIMULATION 600 $3 $CONFIGURATION_FILE $4